package pack_forms;

import java.awt.*;
import java.awt.event.KeyEvent;
import javax.swing.*;
import pack_class.Login;
import pack_class.TextPrompt;

public class frmLogin extends javax.swing.JFrame {
 private Component confirmation;
    private String usuario,password;
	
	public frmLogin() {
		initComponents();
		this.setLocationRelativeTo(null);
		txtusuario.setFocusable(true);
		TextPrompt letrafantasma = new TextPrompt("Usuario",txtusuario);
		TextPrompt letrafantasma1 = new TextPrompt("Contraseña",txtpassword);
	}
	public void datos(String us, String pas){
   usuario = "Admin"; 
   password = "admin";
}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userbig = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        imgpassword = new javax.swing.JLabel();
        imgusuario = new javax.swing.JLabel();
        campopassword = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        campousuario = new javax.swing.JLabel();
        fondito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(830, 475));
        setMinimumSize(new java.awt.Dimension(830, 475));
        setPreferredSize(new java.awt.Dimension(836, 475));
        setResizable(false);
        setSize(new java.awt.Dimension(830, 480));
        getContentPane().setLayout(null);

        userbig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/uwu.png"))); // NOI18N
        getContentPane().add(userbig);
        userbig.setBounds(310, 40, 220, 230);

        txtpassword.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtpassword.setBorder(null);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtpassword);
        txtpassword.setBounds(340, 320, 210, 40);

        txtusuario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtusuario.setBorder(null);
        getContentPane().add(txtusuario);
        txtusuario.setBounds(340, 270, 200, 40);

        imgpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/passwordimg.png"))); // NOI18N
        getContentPane().add(imgpassword);
        imgpassword.setBounds(300, 320, 25, 40);

        imgusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarioimg.png"))); // NOI18N
        getContentPane().add(imgusuario);
        imgusuario.setBounds(300, 270, 30, 40);

        campopassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campos.png"))); // NOI18N
        campopassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campopassword);
        campopassword.setBounds(290, 320, 260, 40);

        btningresar.setBackground(new java.awt.Color(255, 255, 153));
        btningresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btningresar.setForeground(new java.awt.Color(102, 102, 102));
        btningresar.setText("Ingresar");
        btningresar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        getContentPane().add(btningresar);
        btningresar.setBounds(350, 370, 140, 60);

        campousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campos.png"))); // NOI18N
        campousuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(campousuario);
        campousuario.setBounds(290, 270, 260, 40);

        fondito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FINAL.jpg"))); // NOI18N
        fondito.setMaximumSize(new java.awt.Dimension(830, 480));
        fondito.setMinimumSize(new java.awt.Dimension(830, 480));
        getContentPane().add(fondito);
        fondito.setBounds(0, 0, 830, 464);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
    
	String usuario = txtusuario.getText();
	String password = txtpassword.getText();
	 
	if(usuario.isEmpty() || password.isEmpty())
	{
		JOptionPane.showMessageDialog(null, "Algun campo esta vacio");
	}
	else 
	{
            
		if(usuario.equals("Admin") && password.equals("admin")){
                    
			frmMenu c= new frmMenu();
                        c.setVisible(true);
                        this.setVisible(false); 
                        
                        
		}
		else{
		JOptionPane.showMessageDialog(null, "Su usuario o contraseña es incorrecto");
		}
	}
		
		
		
		
    }//GEN-LAST:event_btningresarActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
        String usuario = txtusuario.getText();
	String password = txtpassword.getText();
	 
	if(usuario.isEmpty() || password.isEmpty())
	{
		JOptionPane.showMessageDialog(null, "Algun campo esta vacio");
	}
	else 
	{
            
		if(usuario.equals("Admin") && password.equals("admin")){
                    
			frmMenu c= new frmMenu();
                        c.setVisible(true);
                        this.setVisible(false); 
		}
		else{
		JOptionPane.showMessageDialog(null, "Su usuario o contraseña es incorrecto");
		}
	}
        
        }
    }//GEN-LAST:event_txtpasswordKeyPressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmLogin().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JLabel campopassword;
    private javax.swing.JLabel campousuario;
    private javax.swing.JLabel fondito;
    private javax.swing.JLabel imgpassword;
    private javax.swing.JLabel imgusuario;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JLabel userbig;
    // End of variables declaration//GEN-END:variables
}
