
package pack_forms;
import java.awt.*;
import java.awt.print.*;
import javax.swing.JFrame;


public class frmMenu extends javax.swing.JFrame implements Printable{

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        btncoti = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnrepuestos = new javax.swing.JButton();
        btnregistro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        userimg = new javax.swing.JLabel();
        fondito = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-jinbei-cotizar (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1230, 610, 290, 190);

        btncoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coti (1) (1).png"))); // NOI18N
        btncoti.setBorder(null);
        btncoti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncoti.setOpaque(true);
        btncoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncotiActionPerformed(evt);
            }
        });
        getContentPane().add(btncoti);
        btncoti.setBounds(660, 170, 480, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/geely (1).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1240, 40, 290, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/incamotors (1).png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1250, 240, 290, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-jmc_v-12.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1240, 440, 290, 190);

        btnrepuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regi (1).png"))); // NOI18N
        btnrepuestos.setBorder(null);
        btnrepuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnrepuestos.setOpaque(true);
        btnrepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrepuestosActionPerformed(evt);
            }
        });
        getContentPane().add(btnrepuestos);
        btnrepuestos.setBounds(660, 370, 490, 180);

        btnregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/repuestos (1).png"))); // NOI18N
        btnregistro.setBorder(null);
        btnregistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistro.setOpaque(true);
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistro);
        btnregistro.setBounds(660, 580, 490, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevotaller_01 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 580, 400, 210);

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura (6).png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(250, 30, 6290, 128);

        userimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/owo.jpeg"))); // NOI18N
        getContentPane().add(userimg);
        userimg.setBounds(110, 170, 390, 390);

        fondito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GAAAAA.jpg"))); // NOI18N
        getContentPane().add(fondito);
        fondito.setBounds(0, -20, 1740, 920);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(jMenuBar1.getFont().deriveFont((jMenuBar1.getFont().getStyle() & ~java.awt.Font.ITALIC) & ~java.awt.Font.BOLD, 23));

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       //sad
    }//GEN-LAST:event_jMenu1ActionPerformed
    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        //REGRESAR A LOGIN (OPCION)
        
        /*frmLogin m = new frmLogin();
        m.setVisible(true);
        this.setVisible(false);*/
        System.exit(0);
        

    }//GEN-LAST:event_jmiSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        /*frmLogin m = new frmLogin();
        m.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_formWindowClosing

    private void btncotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncotiActionPerformed
        frmCotizacion l = new frmCotizacion();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncotiActionPerformed

    private void btnrepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrepuestosActionPerformed
        frmTrabajador m3=new frmTrabajador();
	m3.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btnrepuestosActionPerformed

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        frmRepuestos gaa= new frmRepuestos();
        gaa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnregistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncoti;
    private javax.swing.JButton btnregistro;
    private javax.swing.JButton btnrepuestos;
    private javax.swing.JLabel fondito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JLabel userimg;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics grphcs, PageFormat pf, int i) throws PrinterException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
