/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack_forms;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pack_class.Trabajador;

/**
 *
 * @author Mariano PC
 */
public class frmTrabajador extends javax.swing.JFrame {

   DefaultTableModel modelo =  new DefaultTableModel();
    private int fila;
   
   private void columnasTabla(){
            modelo.addColumn("CODIGO");
            modelo.addColumn("NOMBRE");
            modelo.addColumn("APELLDIO");
            modelo.addColumn("DNI");
            modelo.addColumn("TELEFONO");
             modelo.addColumn("FECHA DE NAC.");
            tblTraTabla.setModel(modelo);
   }
            
     public final void leerTrabajador(){
        try{
            File archivo = new File("src\\ficheros\\trabajador.txt");
            if(archivo.exists()){
                FileReader reader = new FileReader(archivo);
                BufferedReader br = new BufferedReader(reader);
                
                String linea;
                while((linea = br.readLine())!=null){
                    StringTokenizer st = new StringTokenizer(linea,";");
                    String cod = st.nextToken().trim();
                    String nom = st.nextToken().trim();
                    String ape = st.nextToken().trim();
                    String dni = st.nextToken().trim();
                    String tel = st.nextToken().trim();
                    String fec = st.nextToken().trim();
                    
                    
                    
                    Object[] obj = new Object[]{
                        cod, nom, ape, dni, tel, fec
                    };
                    modelo.addRow(obj);
                }
                //liberar recursos
                br.close();
            }
            else{
                JOptionPane.showMessageDialog(null, 
                        "No se encuentra la ruta del archivo");
            }
            
        }catch(IOException ex){
            JOptionPane.showMessageDialog(null,
                "Error Leer Fichero:\n"+ ex.getMessage());
        }
    }
            
        
    public frmTrabajador() {
        initComponents();
        columnasTabla();
        leerTrabajador();
        this.setMinimumSize(new Dimension(685,450));
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        txtTraCodigo = new javax.swing.JTextField();
        txtTraNombre = new javax.swing.JTextField();
        txtTraApellido = new javax.swing.JTextField();
        txtTraDNI = new javax.swing.JTextField();
        txtTraTelefono = new javax.swing.JTextField();
        dtcTraFechaNac = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraTabla = new javax.swing.JTable();
        btnTraRegistrar = new javax.swing.JButton();
        btnTraModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(4);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 50, 14);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 50, 50, 14);

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 80, 60, 14);

        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 110, 30, 14);

        jLabel5.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 170, 120, 14);

        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 140, 60, 14);

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar);
        btncancelar.setBounds(480, 210, 130, 23);

        txtTraCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTraCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTraCodigo);
        txtTraCodigo.setBounds(250, 10, 170, 26);

        txtTraNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTraNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtTraNombre);
        txtTraNombre.setBounds(250, 40, 170, 26);

        txtTraApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraApellidoActionPerformed(evt);
            }
        });
        txtTraApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTraApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTraApellido);
        txtTraApellido.setBounds(250, 70, 170, 26);

        txtTraDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTraDNIKeyTyped(evt);
            }
        });
        getContentPane().add(txtTraDNI);
        txtTraDNI.setBounds(250, 100, 170, 26);

        txtTraTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTraTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTraTelefono);
        txtTraTelefono.setBounds(250, 130, 170, 26);
        getContentPane().add(dtcTraFechaNac);
        dtcTraFechaNac.setBounds(250, 160, 190, 26);

        tblTraTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTraTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTraTabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 250, 620, 114);

        btnTraRegistrar.setBackground(new java.awt.Color(255, 102, 0));
        btnTraRegistrar.setText("Registrar");
        btnTraRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTraRegistrar);
        btnTraRegistrar.setBounds(60, 210, 130, 23);

        btnTraModificar.setBackground(new java.awt.Color(0, 153, 255));
        btnTraModificar.setText("Modificar");
        btnTraModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTraModificarMouseClicked(evt);
            }
        });
        btnTraModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTraModificar);
        btnTraModificar.setBounds(280, 210, 130, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GAAAAA.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-30, -70, 750, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTraApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraApellidoActionPerformed

    private void btnTraRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraRegistrarActionPerformed
SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
        try{
    FileWriter fw; //para escribir
    PrintWriter pw;//para impirimir
    
    //creando archivo (con ubicacion)
    fw = new FileWriter("src\\ficheros\\trabajador.txt",true);
    //imprimir archivo
    pw= new PrintWriter(fw);

    
    Trabajador obj = new Trabajador();

    obj.setTra_codigo(Integer.parseInt(txtTraCodigo.getText()));
    obj.setTra_nombre(txtTraNombre.getText());
    obj.setTra_apellido(txtTraApellido.getText());
    obj.setTra_dni(Integer.parseInt(txtTraDNI.getText()));
    obj.setTra_telefono(Integer.parseInt(txtTraTelefono.getText()));
    String date=dFormat.format(dtcTraFechaNac.getDate());
   
    
//eniviar datos al archivo

pw.println(obj.getTra_codigo()+";"+
        obj.getTra_nombre()+";"+
        obj.getTra_apellido()+";"+
        obj.getTra_dni()+";"+
        obj.getTra_telefono()+";"+
        date+";"
        
);
            //cerar la impresion
            pw.close();
            //enciar mensaje de exito
            JOptionPane.showMessageDialog(null,"Se registraron los datos con exito");

//eniviar daotos a la tabla
Object[] fila =new Object[6];

fila[0]=obj.getTra_codigo();
fila[1]=obj.getTra_nombre();
fila[2]=obj.getTra_apellido();
fila[3]=obj.getTra_dni();
fila[4]=obj.getTra_telefono();
fila[5]=date;
modelo.addRow(fila);



}catch(Exception ex) {//se atrapa los errores y si se soluciona
       //enviar mensaje de fracaso
       JOptionPane.showMessageDialog(null, 
               "Error Fichero: " + ex.getMessage());
       }   
//limpiar

txtTraCodigo.setText(null);
txtTraNombre.setText(null);
txtTraApellido.setText(null);
txtTraDNI.setText(null);
txtTraTelefono.setText(null);

txtTraCodigo.requestFocus();

      
    }//GEN-LAST:event_btnTraRegistrarActionPerformed

    private void btnTraModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTraModificarMouseClicked

    }//GEN-LAST:event_btnTraModificarMouseClicked

    private void btnTraModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraModificarActionPerformed
   String []datos=new String[6];
   datos[0]=txtTraCodigo.getText();
   datos[1]=txtTraNombre.getText();
   datos[2]=txtTraApellido.getText();
   datos[3]=txtTraDNI.getText();
   datos[4]=txtTraTelefono.getText();
   datos[5]=dtcTraFechaNac.getDateFormatString();
        for(int i=0; i < tblTraTabla.getColumnCount();i++)
        {
            modelo.setValueAt(datos[i],fila, i);
        }
    }//GEN-LAST:event_btnTraModificarActionPerformed

    private void tblTraTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraTablaMouseClicked
     int fila_Trabajador=tblTraTabla.getSelectedRow();
txtTraCodigo.setText(tblTraTabla.getValueAt(fila_Trabajador,0).toString());
txtTraNombre.setText(tblTraTabla.getValueAt(fila_Trabajador,1).toString());
txtTraApellido.setText(tblTraTabla.getValueAt(fila_Trabajador,2).toString());
txtTraDNI.setText(tblTraTabla.getValueAt(fila_Trabajador,3).toString());
txtTraTelefono.setText(tblTraTabla.getValueAt(fila_Trabajador,4).toString());
fila=fila_Trabajador;
    }//GEN-LAST:event_tblTraTablaMouseClicked

    private void txtTraCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraCodigoKeyTyped
        char code = evt.getKeyChar();
        if(code<'0' || code>'9') evt.consume();
    }//GEN-LAST:event_txtTraCodigoKeyTyped

    private void txtTraNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraNombreKeyTyped

        char nom= evt.getKeyChar();
        //if(Character.isDigit(nom))evt.consume();
        if((nom<'a' || nom>'z') && (nom<'A' || nom>'Z')) evt.consume();
        
    }//GEN-LAST:event_txtTraNombreKeyTyped

    private void txtTraApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraApellidoKeyTyped
          char ape= evt.getKeyChar();
if((ape<'a' || ape>'z') && (ape<'A' || ape>'Z')) evt.consume();
    }//GEN-LAST:event_txtTraApellidoKeyTyped

    private void txtTraDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraDNIKeyTyped
        char dni = evt.getKeyChar();
if(dni<'0' || dni>'9') evt.consume();
    }//GEN-LAST:event_txtTraDNIKeyTyped

    private void txtTraTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraTelefonoKeyTyped
       char tel = evt.getKeyChar();
if(tel<'0' || tel>'9') evt.consume();
    }//GEN-LAST:event_txtTraTelefonoKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frmMenu p = new frmMenu();
        p.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        
        txtTraCodigo.setText(null);
        txtTraNombre.setText(null);
        txtTraApellido.setText(null);
        txtTraDNI.setText(null);
        txtTraTelefono.setText(null);
        dtcTraFechaNac.setCalendar(null);
        
        txtTraCodigo.requestFocus();
        
        
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraModificar;
    private javax.swing.JButton btnTraRegistrar;
    private javax.swing.JButton btncancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dtcTraFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTraTabla;
    private javax.swing.JTextField txtTraApellido;
    private javax.swing.JTextField txtTraCodigo;
    private javax.swing.JTextField txtTraDNI;
    private javax.swing.JTextField txtTraNombre;
    private javax.swing.JTextField txtTraTelefono;
    // End of variables declaration//GEN-END:variables
}
